# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mpoulin/dev/asteroids/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mpoulin/dev/asteroids/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mpoulin/dev/asteroids/src/CMakeFiles /Users/mpoulin/dev/asteroids/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mpoulin/dev/asteroids/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asteroids

# Build rule for target.
asteroids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asteroids
.PHONY : asteroids

# fast build rule for target.
asteroids/fast:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/build
.PHONY : asteroids/fast

components/bounding_box_component.o: components/bounding_box_component.cc.o

.PHONY : components/bounding_box_component.o

# target to build an object file
components/bounding_box_component.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/bounding_box_component.cc.o
.PHONY : components/bounding_box_component.cc.o

components/bounding_box_component.i: components/bounding_box_component.cc.i

.PHONY : components/bounding_box_component.i

# target to preprocess a source file
components/bounding_box_component.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/bounding_box_component.cc.i
.PHONY : components/bounding_box_component.cc.i

components/bounding_box_component.s: components/bounding_box_component.cc.s

.PHONY : components/bounding_box_component.s

# target to generate assembly for a file
components/bounding_box_component.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/bounding_box_component.cc.s
.PHONY : components/bounding_box_component.cc.s

components/component.o: components/component.cc.o

.PHONY : components/component.o

# target to build an object file
components/component.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/component.cc.o
.PHONY : components/component.cc.o

components/component.i: components/component.cc.i

.PHONY : components/component.i

# target to preprocess a source file
components/component.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/component.cc.i
.PHONY : components/component.cc.i

components/component.s: components/component.cc.s

.PHONY : components/component.s

# target to generate assembly for a file
components/component.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/component.cc.s
.PHONY : components/component.cc.s

components/physics_component.o: components/physics_component.cc.o

.PHONY : components/physics_component.o

# target to build an object file
components/physics_component.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/physics_component.cc.o
.PHONY : components/physics_component.cc.o

components/physics_component.i: components/physics_component.cc.i

.PHONY : components/physics_component.i

# target to preprocess a source file
components/physics_component.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/physics_component.cc.i
.PHONY : components/physics_component.cc.i

components/physics_component.s: components/physics_component.cc.s

.PHONY : components/physics_component.s

# target to generate assembly for a file
components/physics_component.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/physics_component.cc.s
.PHONY : components/physics_component.cc.s

components/screen_position_component.o: components/screen_position_component.cc.o

.PHONY : components/screen_position_component.o

# target to build an object file
components/screen_position_component.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/screen_position_component.cc.o
.PHONY : components/screen_position_component.cc.o

components/screen_position_component.i: components/screen_position_component.cc.i

.PHONY : components/screen_position_component.i

# target to preprocess a source file
components/screen_position_component.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/screen_position_component.cc.i
.PHONY : components/screen_position_component.cc.i

components/screen_position_component.s: components/screen_position_component.cc.s

.PHONY : components/screen_position_component.s

# target to generate assembly for a file
components/screen_position_component.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/screen_position_component.cc.s
.PHONY : components/screen_position_component.cc.s

components/sprite_component.o: components/sprite_component.cc.o

.PHONY : components/sprite_component.o

# target to build an object file
components/sprite_component.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/sprite_component.cc.o
.PHONY : components/sprite_component.cc.o

components/sprite_component.i: components/sprite_component.cc.i

.PHONY : components/sprite_component.i

# target to preprocess a source file
components/sprite_component.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/sprite_component.cc.i
.PHONY : components/sprite_component.cc.i

components/sprite_component.s: components/sprite_component.cc.s

.PHONY : components/sprite_component.s

# target to generate assembly for a file
components/sprite_component.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/components/sprite_component.cc.s
.PHONY : components/sprite_component.cc.s

engine/engine.o: engine/engine.cc.o

.PHONY : engine/engine.o

# target to build an object file
engine/engine.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/engine/engine.cc.o
.PHONY : engine/engine.cc.o

engine/engine.i: engine/engine.cc.i

.PHONY : engine/engine.i

# target to preprocess a source file
engine/engine.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/engine/engine.cc.i
.PHONY : engine/engine.cc.i

engine/engine.s: engine/engine.cc.s

.PHONY : engine/engine.s

# target to generate assembly for a file
engine/engine.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/engine/engine.cc.s
.PHONY : engine/engine.cc.s

entity/entity_manager.o: entity/entity_manager.cc.o

.PHONY : entity/entity_manager.o

# target to build an object file
entity/entity_manager.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/entity/entity_manager.cc.o
.PHONY : entity/entity_manager.cc.o

entity/entity_manager.i: entity/entity_manager.cc.i

.PHONY : entity/entity_manager.i

# target to preprocess a source file
entity/entity_manager.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/entity/entity_manager.cc.i
.PHONY : entity/entity_manager.cc.i

entity/entity_manager.s: entity/entity_manager.cc.s

.PHONY : entity/entity_manager.s

# target to generate assembly for a file
entity/entity_manager.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/entity/entity_manager.cc.s
.PHONY : entity/entity_manager.cc.s

game.o: game.cc.o

.PHONY : game.o

# target to build an object file
game.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/game.cc.o
.PHONY : game.cc.o

game.i: game.cc.i

.PHONY : game.i

# target to preprocess a source file
game.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/game.cc.i
.PHONY : game.cc.i

game.s: game.cc.s

.PHONY : game.s

# target to generate assembly for a file
game.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/game.cc.s
.PHONY : game.cc.s

graphics/texture.o: graphics/texture.cc.o

.PHONY : graphics/texture.o

# target to build an object file
graphics/texture.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture.cc.o
.PHONY : graphics/texture.cc.o

graphics/texture.i: graphics/texture.cc.i

.PHONY : graphics/texture.i

# target to preprocess a source file
graphics/texture.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture.cc.i
.PHONY : graphics/texture.cc.i

graphics/texture.s: graphics/texture.cc.s

.PHONY : graphics/texture.s

# target to generate assembly for a file
graphics/texture.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture.cc.s
.PHONY : graphics/texture.cc.s

graphics/texture_manager.o: graphics/texture_manager.cc.o

.PHONY : graphics/texture_manager.o

# target to build an object file
graphics/texture_manager.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture_manager.cc.o
.PHONY : graphics/texture_manager.cc.o

graphics/texture_manager.i: graphics/texture_manager.cc.i

.PHONY : graphics/texture_manager.i

# target to preprocess a source file
graphics/texture_manager.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture_manager.cc.i
.PHONY : graphics/texture_manager.cc.i

graphics/texture_manager.s: graphics/texture_manager.cc.s

.PHONY : graphics/texture_manager.s

# target to generate assembly for a file
graphics/texture_manager.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/graphics/texture_manager.cc.s
.PHONY : graphics/texture_manager.cc.s

input/keyboard.o: input/keyboard.cc.o

.PHONY : input/keyboard.o

# target to build an object file
input/keyboard.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/input/keyboard.cc.o
.PHONY : input/keyboard.cc.o

input/keyboard.i: input/keyboard.cc.i

.PHONY : input/keyboard.i

# target to preprocess a source file
input/keyboard.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/input/keyboard.cc.i
.PHONY : input/keyboard.cc.i

input/keyboard.s: input/keyboard.cc.s

.PHONY : input/keyboard.s

# target to generate assembly for a file
input/keyboard.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/input/keyboard.cc.s
.PHONY : input/keyboard.cc.s

messages/message.o: messages/message.cc.o

.PHONY : messages/message.o

# target to build an object file
messages/message.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/messages/message.cc.o
.PHONY : messages/message.cc.o

messages/message.i: messages/message.cc.i

.PHONY : messages/message.i

# target to preprocess a source file
messages/message.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/messages/message.cc.i
.PHONY : messages/message.cc.i

messages/message.s: messages/message.cc.s

.PHONY : messages/message.s

# target to generate assembly for a file
messages/message.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/messages/message.cc.s
.PHONY : messages/message.cc.s

systems/input_system.o: systems/input_system.cc.o

.PHONY : systems/input_system.o

# target to build an object file
systems/input_system.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/input_system.cc.o
.PHONY : systems/input_system.cc.o

systems/input_system.i: systems/input_system.cc.i

.PHONY : systems/input_system.i

# target to preprocess a source file
systems/input_system.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/input_system.cc.i
.PHONY : systems/input_system.cc.i

systems/input_system.s: systems/input_system.cc.s

.PHONY : systems/input_system.s

# target to generate assembly for a file
systems/input_system.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/input_system.cc.s
.PHONY : systems/input_system.cc.s

systems/interpolation_system.o: systems/interpolation_system.cc.o

.PHONY : systems/interpolation_system.o

# target to build an object file
systems/interpolation_system.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/interpolation_system.cc.o
.PHONY : systems/interpolation_system.cc.o

systems/interpolation_system.i: systems/interpolation_system.cc.i

.PHONY : systems/interpolation_system.i

# target to preprocess a source file
systems/interpolation_system.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/interpolation_system.cc.i
.PHONY : systems/interpolation_system.cc.i

systems/interpolation_system.s: systems/interpolation_system.cc.s

.PHONY : systems/interpolation_system.s

# target to generate assembly for a file
systems/interpolation_system.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/interpolation_system.cc.s
.PHONY : systems/interpolation_system.cc.s

systems/movement_system.o: systems/movement_system.cc.o

.PHONY : systems/movement_system.o

# target to build an object file
systems/movement_system.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/movement_system.cc.o
.PHONY : systems/movement_system.cc.o

systems/movement_system.i: systems/movement_system.cc.i

.PHONY : systems/movement_system.i

# target to preprocess a source file
systems/movement_system.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/movement_system.cc.i
.PHONY : systems/movement_system.cc.i

systems/movement_system.s: systems/movement_system.cc.s

.PHONY : systems/movement_system.s

# target to generate assembly for a file
systems/movement_system.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/movement_system.cc.s
.PHONY : systems/movement_system.cc.s

systems/physics_system.o: systems/physics_system.cc.o

.PHONY : systems/physics_system.o

# target to build an object file
systems/physics_system.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/physics_system.cc.o
.PHONY : systems/physics_system.cc.o

systems/physics_system.i: systems/physics_system.cc.i

.PHONY : systems/physics_system.i

# target to preprocess a source file
systems/physics_system.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/physics_system.cc.i
.PHONY : systems/physics_system.cc.i

systems/physics_system.s: systems/physics_system.cc.s

.PHONY : systems/physics_system.s

# target to generate assembly for a file
systems/physics_system.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/physics_system.cc.s
.PHONY : systems/physics_system.cc.s

systems/rendering_system.o: systems/rendering_system.cc.o

.PHONY : systems/rendering_system.o

# target to build an object file
systems/rendering_system.cc.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/rendering_system.cc.o
.PHONY : systems/rendering_system.cc.o

systems/rendering_system.i: systems/rendering_system.cc.i

.PHONY : systems/rendering_system.i

# target to preprocess a source file
systems/rendering_system.cc.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/rendering_system.cc.i
.PHONY : systems/rendering_system.cc.i

systems/rendering_system.s: systems/rendering_system.cc.s

.PHONY : systems/rendering_system.s

# target to generate assembly for a file
systems/rendering_system.cc.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/systems/rendering_system.cc.s
.PHONY : systems/rendering_system.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... asteroids"
	@echo "... components/bounding_box_component.o"
	@echo "... components/bounding_box_component.i"
	@echo "... components/bounding_box_component.s"
	@echo "... components/component.o"
	@echo "... components/component.i"
	@echo "... components/component.s"
	@echo "... components/physics_component.o"
	@echo "... components/physics_component.i"
	@echo "... components/physics_component.s"
	@echo "... components/screen_position_component.o"
	@echo "... components/screen_position_component.i"
	@echo "... components/screen_position_component.s"
	@echo "... components/sprite_component.o"
	@echo "... components/sprite_component.i"
	@echo "... components/sprite_component.s"
	@echo "... engine/engine.o"
	@echo "... engine/engine.i"
	@echo "... engine/engine.s"
	@echo "... entity/entity_manager.o"
	@echo "... entity/entity_manager.i"
	@echo "... entity/entity_manager.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... graphics/texture.o"
	@echo "... graphics/texture.i"
	@echo "... graphics/texture.s"
	@echo "... graphics/texture_manager.o"
	@echo "... graphics/texture_manager.i"
	@echo "... graphics/texture_manager.s"
	@echo "... input/keyboard.o"
	@echo "... input/keyboard.i"
	@echo "... input/keyboard.s"
	@echo "... messages/message.o"
	@echo "... messages/message.i"
	@echo "... messages/message.s"
	@echo "... systems/input_system.o"
	@echo "... systems/input_system.i"
	@echo "... systems/input_system.s"
	@echo "... systems/interpolation_system.o"
	@echo "... systems/interpolation_system.i"
	@echo "... systems/interpolation_system.s"
	@echo "... systems/movement_system.o"
	@echo "... systems/movement_system.i"
	@echo "... systems/movement_system.s"
	@echo "... systems/physics_system.o"
	@echo "... systems/physics_system.i"
	@echo "... systems/physics_system.s"
	@echo "... systems/rendering_system.o"
	@echo "... systems/rendering_system.i"
	@echo "... systems/rendering_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

